type BlockInfo {
  id: ID!
  hash: String!
  height: Int
  time: Timestamp
}

type Transfer {
  id: ID! # transactionHash-index
  transactionHash: String!
  slot: Int!
  timestamp: Timestamp!
  sender: String!
  receiver: String!
  mint: String!
  symbol: String!
  amount: BigInt! # Raw amount
  amountDisplay: BigDecimal! # UI amount
}

type TransferSummary {
  id: ID! # Timestamp of the start of the minute (bucket)
  minute: String! # ISO timestamp
  totalTransfers: Int!
  totalVolumeUSD: BigDecimal!
  usdcTransfers: Int!
  usdtTransfers: Int!
  usdcVolumeUSD: BigDecimal!
  usdtVolumeUSD: BigDecimal!
}
